name: Register API Definition to Azure API Center
on:
  workflow_dispatch:
    inputs:
      file-location:
        description: 'API Definition file location'
        required: true
        default: 'api/v3.0/api-with-examples.json'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Please configure the environment name required in federated identity credential
    # https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#creating-an-environment
    environment: staging
    steps:
      - uses: actions/checkout@v4

      # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure
      # https://github.com/marketplace/actions/azure-login#login-with-openid-connect-oidc-recommended
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: 1d642a4f-60b6-4d22-9dd7-eeb8e1d801e1
          enable-AzPSSession: true

      # Please create following environment variables to deploy to azure resource: RESOURCE_GROUP, RESOURCE_NAME, FILE_LOCATION
      # RESOURCE_GROUP: Azure Resource Group name, please ensure the resource group already created.
      # RESOURCE_NAME: Azure API Center resource name, please ensure the API Center resource already created.
      # FILE_LOCATION: API Definition file location
      # https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-a-repository
      - name: Deploy to API Center
        uses: azure/CLI@v2
        with:
          azcliversion: latest
          inlineScript: |
            az extension add --name apic-extension --version 1.0.0
            az apic api register -g wenytang -n wenytestapic003 --api-location ${{ github.event.inputs.file-location }}
